articles/urls.py
from django.urls import path
from .views import list_articles, article_detail, article_search, create

app_name = 'articles'

urlpatterns = [
    path('', list_articles, name='article_list'),
    path('article/<int:id>/', article_detail, name='article_detail'),
    path('search/', article_search, name='article_search'),
    path('create/', create, name='create'),


]

campos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.shortcuts import render
from accounts.views import login_view, logout_view

urlpatterns = [
    path('', login_view, name='login'),
    path('', logout_view, name='logout'),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),

]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()

    def __str__(self):
        return self.title

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import (
    authenticate,
    login,
    logout,
)


# Create your views here.
def login_view(request):
    context = {

    }
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is None:
            context.update({'error': 'invalid username or password'})
        else:
            login(request, user=user)
            return redirect('/articles')

    return render(request, 'account/login.html', context)


def logout_view(request):
    logout(request)
    return redirect('/')

articles/views.py
from django.shortcuts import render
from .models import Article
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


def list_articles(request):
    articles = Article.objects.all()
    context = {
        "articles": articles,
    }
    articles_string = render_to_string('articles/articles_list.html', context=context)
    return HttpResponse(articles_string)


def article_detail(request, *args, **kwargs):
    pk = kwargs.pop('id')
    article = Article.objects.get(id=pk)
    context = {
        'article': article,
    }
    article_string = render_to_string('articles/article_detail.html', context)
    return HttpResponse(article_string)


def article_search(request):
    pk = request.GET.get('q')
    article = Article.objects.get(id=pk)
    context = {
        'article': article,
    }
    article_string = render_to_string('articles/article_search.html', context)
    return HttpResponse(article_string)


@login_required
def create(request):
    context = {}
    if request.method == "POST":
        data = request.POST
        title = data.get('title')
        content = data.get('content')
        article = Article.objects.create(title=title, content=content)
        context = {
            'article': article,
            'created': True,
        }

    return render(request, 'articles/create.html', context)

templates/articles/article_detail.html
{% extends 'base.html' %}

{% block content %}

    <div style="text-align: center">
    <h1>{{ article.title }}</h1>
    <p>{{ article.content }}</p>
    </div>
{% endblock content %}

templates/articles/article_search.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ article.title }}</h1>
    <p>{{ article.content }}</p>

{% endblock content %}

templates/articles/articles_list.html
{% extends 'base.html' %}
{% block extra_css %}
    .card {
    /* Add shadows to create the "card" effect */
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    }

    /* On mouse-over, add a deeper shadow */
    .card:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
    }

    /* Add some padding inside the card container */
    .container {
    padding: 2px 16px;
    }
{% endblock extra_css %}
{% block content %}



    {% for article in articles %}
        <div style="margin-bottom: 10px">
        <a href="article/{{ article.id }}/">
            <div class="card">

                <div class="container">
                    <h4><b>{{ article.title }}</b></h4>
                    <p>{{ article.content }}</p>
                </div>
            </div>
        </a>
        </div>

    {% endfor %}


{% endblock content %}

templates/articles/create.html
{% extends 'base.html' %}


{% block content %}


    {% if not created %}

    <form action="{% url 'articles:create' %}" method="post">
        {% csrf_token %}
        <div style="margin-top: 20px">
             <input type="text" name="title" placeholder="enter title"/>
        </div>
       <div style="margin-top: 10px">
              <textarea name="content" placeholder="enter content"></textarea>
       </div>

        <button style="margin-top: 10px" type="submit">Creat article</button>

    </form>

    {% else %}
    <a href="{% url 'articles:article_detail'  article.id  %}">
    {{ article.title }}
    </a>
    {% endif %}






{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
    * {
        margin: 0;
        padding: 0;
    }


    body {
        font-family: 'Raleway', sans-serif;
    }

    #ribbon {
        position: absolute;
        background-color: red;
        color: white;
        top: 40px;
        left: -30px;
        width: 160px;
        transform: rotate(-45deg);
        text-align: center;
    }

    #container {
        position: relative;
        width: 80%;
        margin: 5% auto;
        background-color: #ad82a9;
        box-shadow: -2px -2px 5px white, 2px -2px 5px white;
    }

    #container > nav {
        width: 100%;
        display: flex;
        max-height: 60px;
    }

    #logo {
        line-height: 60px;
        font-size: 30px;
        padding: 0 50px;
        color: white;
        width: 40%;
        letter-spacing: 2px;
        text-shadow: 2px 2px 5px;
    }

    #container > nav > ul {
        margin: 0;
        paddding: 0;
        list-style-type: none;
        display: flex;
        position: absolute;
        right: 50px;
        /*   min-width:60%; */
    }

    #container > nav > ul > li {
        line-height: 60px;
        margin: 0 0px;
        padding: 0;
        text-align: center;
        display: inline-block;

        /*   background-color:green; */
        min-width: 120px;

    }

    #container > nav > ul > li > a {
        position: relative;
        /*   background-color:red; */
        margin: 0 20px;
        color: white;
    }

    #container > nav > ul > li:hover {
        border-bottom: 2px solid white;
        background-color: #0088ff;
    }

    #container > nav > ul > .dropdown:hover {
        border-bottom: none;
    }

    #container > nav > ul > .dropdown:hover > .dd {
        display: block;
    }

    .dropdown:hover > a .fa-caret-down {
        display: none;
    }

    a {
        text-decoration: none;

    }

    #container > nav > ul > li > div {
        position: absolute;
        padding: 0 10px;

        background-color: black;
        display: none;
        background-color: aliceblue;
        min-width: 100px;
    }

    #container > nav > ul > li > div > ul {
        margin: 0px 0 10px 0;
        padding: 0;
        list-style: none;
    }

    #u_a_c {
        position: relative;
        width: 100%;
        /*   background-color:red; */
    }

    #up_arrow {
        position: relative;
        width: 20px;
        height: 20px;
        left: 42%;
        top: -10px;
        background-color: aliceblue;
        transform: rotate(45deg);
    }

    #container > nav > ul > li > div > ul > li:hover {
        background-color: rgba(0, 0, 0, 0.2);
    }

    #container > nav > ul > li > div > ul > li > a {
        padding: 5px;
        color: black;
    }

    {% block extra_css %}
    {% endblock extra_css %}
</style>
<body>

<div>
    <div id="container">

        <nav>
            <div id="logo">
                Company
            </div>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li class="dropdown" onmouseover="hover(this);" onmouseout="out(this);"><a href="#">Gallery &nbsp;<i
                        class="fa fa-caret-down"></i></a>
                    <div class="dd">
                        <div id="up_arrow"></div>
                        <ul>

                            <li><a href="#">2019</a></li>
                            <li><a href="#">2018</a></li>
                            <li><a href="#">2017</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="#">Contact</a></li>
                <li class="dropdown"><a href="#">Others &nbsp;<i class="fa fa-caret-down"></i> </a>
                    <div class="dd">
                        <div id="u_a_c">
                            <div id="up_arrow"></div>
                        </div>
                        <ul>

                            <li><a href="#">DOCS</a></li>
                            <li><a href="#">API</a></li>
                            <li><a href="#">PROJECTS</a></li>
                        </ul>
                    </div>
            </ul>

        </nav>
        <div>
            <form action="{% url 'articles:article_search' %}" method="get">
                <input type="text" name="q" placeholder="search for article ....">
                <input type="submit">

            </form>
        </div>
    </div>
</div>


{% block content %}
{% endblock content %}
</body>
</html>